### PR TITLE
Fix user agent not set properly for factory requests

### LINKED ISSUE #68: User agent not set properly on all Kubernetes requests
The calls made by the [factory builder](https://github.com/TakeScoop/kubectl-exec-forward/blob/6a27445a4c6c62081fcc8f8fe40ed791a650330c/internal/forwarder/config.go#L35-L45) appear to be the culprit. We should either ensure that the user agent is set properly for these requests, find a way to make generic object requests using the basic client-go [clientset](https://github.com/kubernetes/client-go/blob/255c7965135603be097ad4dc482924f869bd4a6a/kubernetes/clientset.go) (might not be possible), or find a way to use the [dynamicResourceClient](https://github.com/kubernetes/client-go/blob/255c7965135603be097ad4dc482924f869bd4a6a/dynamic/simple.go#L63-L95)

### PR DESCRIPTION
**Pull request by ryanwholey**
I noticed that the user agent is set to a default for the factory runtime.Object request. 

```
# good
kubectl-exec-forward/dev
# bad
kubectl-exec-forward/v0.0.0 (darwin/amd64) kubernetes/$Format
```

Changes:
- Moves the client.factory creation into Init, instead of on the New func for the client to take advantage of the passed version string used for the clientset. The factory is used to fetch the generic runtime.Object to handle generic TYPE resources in the CLI arguments.
- Adds an implementation of the `genericclioptions.RESTClientGetter` interface, ensuring that UserAgent is set on the returned rest config.

The stack:
- standard kubectl flags parsed into a generic REST getter([kubect-exec-forward/cmd/forward.go](https://github.com/TakeScoop/kubectl-exec-forward/blob/master/cmd/forward.go#L22))
- the getter is used to create a more specified REST getter ([kubect-exec-forward/cmd/forward.go](https://github.com/TakeScoop/kubectl-exec-forward/blob/master/cmd/forward.go#L38))
- the getter is wrapped for some added functionality ([kubectl/cmd/util/kubectl_match_version.go](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/util/kubectl_match_version.go#L106-L110))
- This enhanced getter is where the rest configuration is generated, although it just calls through to the orginal getter ([kubectl/cmd/util/kubectl_match_version.go](https://github.com/kubernetes/kubectl/blob/ce9f95af72bc760e7eaca946b593ec9f16de389f/pkg/cmd/util/kubectl_match_version.go#L70-L81))
- The enhanced getter calls a set defaults function on the returned rest config ([kubectl/cmd/util/kubectl_match_version.go](https://github.com/kubernetes/kubectl/blob/ce9f95af72bc760e7eaca946b593ec9f16de389f/pkg/cmd/util/kubectl_match_version.go#L79))
- rest defaults are applied, setting the user agent to a default ([client-go/rest/config.go](https://github.com/kubernetes/client-go/blob/255c7965135603be097ad4dc482924f869bd4a6a/rest/config.go#L454-L459))

There doesn't seem to be a way to set the user agent going _in_ to the creation of the REST getter, but we can wrap the getter similar to what they've done with `MatchVersionFlags`. 

To me it seems like the factory approach to generic objects might not be ideal. Maybe we could use the go client's [dynamicResourceClient](https://github.com/kubernetes/client-go/blob/255c7965135603be097ad4dc482924f869bd4a6a/dynamic/simple.go#L63-L95) in its place. It takes a REST config directly instead of a REST getter.

fixes #68

### CODE REVIEW

File: internal/forwarder/rest.go [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+	"k8s.io/apimachinery/pkg/api/meta"
+	"k8s.io/cli-runtime/pkg/genericclioptions"
+	"k8s.io/client-go/discovery"
+	"k8s.io/client-go/rest"
+	"k8s.io/client-go/tools/clientcmd"
+)
+
+// restGetter wraps the passed getter, allowing for extended behavior on the interface methods.
+type restGetter struct {
+	getter    genericclioptions.RESTClientGetter
```
Comment (bendrucker) [inline internal/forwarder/rest.go:13]: Should be a good opportunity to use an embedded struct

**Review by bendrucker — APPROVED** [review]
Great!
